--SEARCH TABLES NAMES FROM A DATABASE
SELECT * FROM INFORMATION_SCHEMA.TABLES 
WHERE TABLE_NAME LIKE '%category%';

--SEARCH TABLE NAMES FROM ALL DATABASES
SELECT name FROM   sys.databases WHERE  CASE
  WHEN state_desc = 'ONLINE' 
  THEN OBJECT_ID(QUOTENAME(name) + '.[dbo].[<table_name>]', 'U')
   END IS NOT NULL;


--SEARCH VIEW NAMES FROM A DATABASE
SELECT * FROM sys.views
WHERE name = '%%';